name: scrape
on:
  workflow_dispatch:
  schedule:
  - cron: '0 8,10,13,16 * * *'   # UTC (7:00 CET = 6:00 UTC en invierno / 5:00 UTC en verano)
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
      - name: Autoclean
        run: sudo apt clean -y && sudo apt autoclean -y && sudo apt autoremove -y
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser
      - name: Install pip packages
        run: pip install -r requirements.txt
      - name: Scraping SIA
        uses: nick-fields/retry@v2
        env:
          IMGUR_CLIENT: ${{ secrets.IMGUR_CLIENT }}
        with:
          timeout_minutes: 60
          retry_wait_seconds: 15
          max_attempts: 3
          retry_on: error
          command: python scraper.py sia
      - name: Scraping ALQ
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          retry_wait_seconds: 15
          max_attempts: 3
          retry_on: error
          command: python scraper.py alq
      - name: Build site
        run: python build_site.py
      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          DT=$(date -u +'%Y-%m-%d %H:%M UTC')
          git commit -m "Automated: ${DT}" || exit 0
          git push
